---
title: "VLAD"
author: "Richard Wilson"
output: html_document
---

```{r vlad prep, results = "asis"}

library(ggpubr)
library(cowplot)
library(tidyverse)

vlad_data <- read.csv('vlad_example_trust.txt')

#fix the encoding issue for column 1
colnames(vlad_data)[1] <- 'case_number'

#for looping over conditions
vlad_data <- vlad_data %>%
  mutate(one_word = 'test',
         DIAG_GROUP = 'test condition') %>%
  arrange(case_number,P_SPELL_DISDATE)

#calculate vlad and excess deaths
vlad_data <- vlad_data %>% 
  mutate(
    vlad =  DIED * -1 + (P_EVENT),
    excess_deaths = DIED - P_EVENT
  )

#NHS digital constants
Rho_u  =  0.5
Rho_l   = 2
h_lower = 4.2
h_upper = -4.2


#feed data table and seed first row
vlads <- vlad_data %>%
  group_by(DIAG_GROUP) %>%
  na.omit(vlad) %>%
  mutate(
    vlad_cusum = cumsum(vlad),
    id = row_number(),
    excess_deaths_cumsum = cumsum(excess_deaths),
    deaths_cumsum = cumsum(DIED), 
    WL_n =  DIED * log(Rho_l) - log( 1 + (Rho_l - 1) * P_EVENT),
    WU_n =  DIED * log(Rho_u) - log( 1 + (Rho_u - 1) * P_EVENT),
    CL_n = ifelse(id == 1, ifelse(WL_n > 0 ,WL_n, 0), NA),
    CU_n = ifelse(id == 1, ifelse(WU_n * -1 < 0 ,WU_n * -1, 0), NA)
  ) 

# for-loop over rows

for(i in 2:nrow(vlads)) {

vlads[i,'CL_n'] =  ifelse(vlads[i-1,'CL_n'] >= h_lower,
                   ifelse(vlads[i,'WL_n'] > 0 ,vlads[i,'WL_n'], 0),
                   ifelse(vlads[i-1,'CL_n'] + vlads[i,'WL_n'] > 0 ,
                          vlads[i-1,'CL_n'] + vlads[i,'WL_n'],0))
 vlads[i,'CU_n'] =  ifelse(vlads[i-1,'CU_n'] <= h_upper,
                   ifelse(vlads[i,'WU_n']*-1 < 0 ,vlads[i,'WU_n']*-1, 0),
                   ifelse(vlads[i-1,'CU_n'] - vlads[i,'WU_n'] < 0 ,vlads[i-1,'CU_n'] - vlads[i,'WU_n'],0))
}

#calculate limits
vlads <- vlads %>%
  mutate(
    LL_n = vlad_cusum + (CL_n - h_lower) / log(Rho_l),
    LU_n = vlad_cusum - (CU_n - h_upper) / log(Rho_u)
  )


#find last entry by diagnosis group
#this is my way of trying to identify deteriorating/improving
filter_last_day <- vlads %>%
group_by(DIAG_GROUP) %>%
  summarise( id = max(id))

vlad_onlastday_list <- inner_join(vlads, filter_last_day)

vlad_worst_list<- vlad_onlastday_list %>%
  filter(LU_n < 0 & 
    deaths_cumsum >=1) %>%
  select(DIAG_GROUP)

vlad_better_list<- vlad_onlastday_list %>%
  filter(LL_n > 0 & 
    deaths_cumsum >=1) %>%
  select(DIAG_GROUP)

vlad_nodifference_list<- vlad_onlastday_list %>%
  filter(LL_n < 0 & LU_n > 0) %>%
  select(DIAG_GROUP)

vlad_worse <- inner_join(vlads, vlad_worst_list)
vlad_better <- inner_join(vlads, vlad_better_list)
vlad_nodifference <- inner_join(vlads, vlad_nodifference_list)

if(nrow(vlad_worse) >0 ){
  vlad_worse_plot <- vlad_worse %>%
    ggplot(aes(x = id, y = vlad_cusum)) +
  geom_line(colour = "red") +
  geom_hline(yintercept = 0, colour = "darkgrey", linetype = 2) +
  geom_line(aes(x = id, y = LL_n), colour = "orange") +
  geom_line(aes(x = id, y = LU_n), colour = "orange") +
  facet_wrap(~one_word, scales = "free")
}

if(nrow(vlad_better) >0 ){
vlad_better_plot <- vlad_better %>%
    ggplot(aes(x = id, y = vlad_cusum)) +
  geom_line(colour = "darkgreen") +
  geom_hline(yintercept = 0, colour = "darkgrey", linetype = 2) +
  geom_line(aes(x = id, y = LL_n), colour = "orange") +
  geom_line(aes(x = id, y = LU_n), colour = "orange") +
  facet_wrap(~one_word, scales = "free")
}

if(nrow(vlad_nodifference) >0 ){
vlad_nodifference_plot <- vlad_nodifference %>%
    ggplot(aes(x = id, y = vlad_cusum)) +
  geom_line(colour = "blue") +
  geom_hline(yintercept = 0, colour = "darkgrey", linetype = 2) +
  geom_line(aes(x = id, y = LL_n), colour = "lightblue") +
  geom_line(aes(x = id, y = LU_n), colour = "lightblue") +
  facet_wrap(~one_word, scales = "free") 
}


vlad_text <- paste("VLAD charts show cumulative survival",
             "line drops when a patient dies",
             "line goes up when a patient survives,",
             "a steady decline implies outcomes are typically worse than expected.",
             "a step change implies something substantial changed",
             "in care, patient case, or coding", sep = "\n")

# Create a text grob
vwtgrob <- text_grob(vlad_text, color = "steelblue")

```

### VLAD improving
```{r vlad better charts, include = TRUE,  fig.hieght = 5, fig.width = 16}
if (nrow(vlad_better) > 0) {
  #plot_grid(vwtgrob, vlad_better_plot, rel_widths = c(1, 3))
  vlad_better_plot
} else {print("No conditions with 1 or more deaths")}
```

### VLAD worsening

```{r vlad worse tab, include = TRUE ,  fig.hieght = 5, fig.width = 16}
if (nrow(vlad_worse) > 0) {
  #plot_grid(vwtgrob, vlad_worse_plot, rel_widths = c(1, 3))
  vlad_worse_plot
} else {print("No conditions with 1 or more deaths")}
```

### VLAD no difference

```{r vlad nodiff tab, include = TRUE ,  fig.hieght = 5, fig.width = 16}
if (nrow(vlad_nodifference) > 0) {
  #plot_grid(vwtgrob, vlad_worse_plot, rel_widths = c(1, 3))
  vlad_nodifference_plot
} else {print("No conditions with 1 or more deaths")}
```